/**
 * Mock data for all database entities.
 * Used to run the application without a real Supabase backend.
 */

const MOCK_USER_ID = 'mock-user-001';
const MOCK_USER_2_ID = 'mock-user-002';
const MOCK_USER_3_ID = 'mock-user-003';
const MOCK_USER_4_ID = 'mock-user-004';
const MOCK_USER_5_ID = 'mock-user-005';
const MOCK_USER_6_ID = 'mock-user-006';
const MOCK_USER_7_ID = 'mock-user-007';
const MOCK_USER_8_ID = 'mock-user-008';
const MOCK_USER_9_ID = 'mock-user-009';
const MOCK_USER_10_ID = 'mock-user-010';
const MOCK_USER_11_ID = 'mock-user-011';
const MOCK_USER_12_ID = 'mock-user-012';
const MOCK_USER_13_ID = 'mock-user-013';

const MOCK_EMPRESA_1_ID = 'mock-empresa-001';
const MOCK_EMPRESA_2_ID = 'mock-empresa-002';
const MOCK_EMPRESA_3_ID = 'mock-empresa-003';
const MOCK_EMPRESA_4_ID = 'mock-empresa-004';
const MOCK_EMPRESA_5_ID = 'mock-empresa-005';
const MOCK_EMPRESA_6_ID = 'mock-empresa-006';
const MOCK_EMPRESA_7_ID = 'mock-empresa-007';
const MOCK_EMPRESA_8_ID = 'mock-empresa-008';
const MOCK_EMPRESA_9_ID = 'mock-empresa-009';
const MOCK_EMPRESA_10_ID = 'mock-empresa-010';
const MOCK_EMPRESA_11_ID = 'mock-empresa-011';
const MOCK_EMPRESA_12_ID = 'mock-empresa-012';

const MOCK_OP_1_ID = 'mock-op-001';
const MOCK_OP_2_ID = 'mock-op-002';
const MOCK_OP_3_ID = 'mock-op-003';
const MOCK_OP_4_ID = 'mock-op-004';
const MOCK_OP_5_ID = 'mock-op-005';
const MOCK_OP_6_ID = 'mock-op-006';
const MOCK_OP_7_ID = 'mock-op-007';
const MOCK_OP_8_ID = 'mock-op-008';
const MOCK_OP_9_ID = 'mock-op-009';
const MOCK_OP_10_ID = 'mock-op-010';

// ===================== PROFILES =====================
export const mockProfiles = [
  {
    id: MOCK_USER_ID,
    nome: 'João Silva',
    email: 'joao@maxcapital.com.br',
    telefone: '(11) 99999-0001',
    tipo: 'parceiro',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'JOAO2024',
    indicado_por_id: null,
    total_indicacoes_diretas: 5,
    total_indicacoes_indiretas: 3,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: MOCK_USER_2_ID,
    nome: 'Maria Santos',
    email: 'maria@empresa.com',
    telefone: '(11) 99999-0002',
    tipo: 'empresa',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'MARIA2024',
    indicado_por_id: MOCK_USER_ID,
    total_indicacoes_diretas: 2,
    total_indicacoes_indiretas: 0,
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: MOCK_USER_3_ID,
    nome: 'Carlos Oliveira',
    email: 'carlos@investidor.com',
    telefone: '(11) 99999-0003',
    tipo: 'investidor',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'CARLOS2024',
    indicado_por_id: MOCK_USER_ID,
    total_indicacoes_diretas: 0,
    total_indicacoes_indiretas: 0,
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: MOCK_USER_4_ID,
    nome: 'Ana Beatriz Costa',
    email: 'ana.costa@parceiro.com',
    telefone: '(21) 98888-1234',
    tipo: 'parceiro',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'ANA2024',
    indicado_por_id: MOCK_USER_ID,
    total_indicacoes_diretas: 3,
    total_indicacoes_indiretas: 1,
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-07-01T10:00:00Z',
  },
  {
    id: MOCK_USER_5_ID,
    nome: 'Ricardo Mendes',
    email: 'ricardo@investimentos.com',
    telefone: '(31) 97777-5678',
    tipo: 'investidor',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'RICARDO2024',
    indicado_por_id: MOCK_USER_4_ID,
    total_indicacoes_diretas: 1,
    total_indicacoes_indiretas: 0,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-08-01T10:00:00Z',
  },
  {
    id: MOCK_USER_6_ID,
    nome: 'Fernanda Lima',
    email: 'fernanda@agro.com.br',
    telefone: '(62) 96666-9012',
    tipo: 'empresa',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'FERNANDA2024',
    indicado_por_id: MOCK_USER_2_ID,
    total_indicacoes_diretas: 0,
    total_indicacoes_indiretas: 0,
    created_at: '2024-04-20T10:00:00Z',
    updated_at: '2024-08-15T10:00:00Z',
  },
  {
    id: MOCK_USER_7_ID,
    nome: 'Pedro Almeida',
    email: 'pedro@admin.maxcapital.com.br',
    telefone: '(11) 95555-3456',
    tipo: 'admin',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'PEDRO2024',
    indicado_por_id: null,
    total_indicacoes_diretas: 0,
    total_indicacoes_indiretas: 0,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-09-01T10:00:00Z',
  },
  {
    id: MOCK_USER_8_ID,
    nome: 'Juliana Rocha',
    email: 'juliana@parceiro.com',
    telefone: '(41) 94444-7890',
    tipo: 'parceiro',
    avatar_url: null,
    status: 'pendente_aprovacao',
    codigo_convite_proprio: 'JULIANA2024',
    indicado_por_id: MOCK_USER_4_ID,
    total_indicacoes_diretas: 0,
    total_indicacoes_indiretas: 0,
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2024-09-01T10:00:00Z',
  },
  {
    id: MOCK_USER_9_ID,
    nome: 'Marcos Vinícius Souza',
    email: 'marcos@energia.com',
    telefone: '(51) 93333-2345',
    tipo: 'empresa',
    avatar_url: null,
    status: 'inativo',
    codigo_convite_proprio: 'MARCOS2024',
    indicado_por_id: MOCK_USER_ID,
    total_indicacoes_diretas: 0,
    total_indicacoes_indiretas: 0,
    created_at: '2024-05-10T10:00:00Z',
    updated_at: '2024-10-01T10:00:00Z',
  },
  {
    id: MOCK_USER_10_ID,
    nome: 'Camila Ferreira',
    email: 'camila@investidor.com.br',
    telefone: '(48) 92222-6789',
    tipo: 'investidor',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'CAMILA2024',
    indicado_por_id: MOCK_USER_5_ID,
    total_indicacoes_diretas: 0,
    total_indicacoes_indiretas: 0,
    created_at: '2024-06-15T10:00:00Z',
    updated_at: '2024-10-15T10:00:00Z',
  },
  {
    id: MOCK_USER_11_ID,
    nome: 'Rafael Drummond',
    email: 'rafael@capitalverde.com.br',
    telefone: '(21) 91111-4567',
    tipo: 'investidor',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'RAFAEL2024',
    indicado_por_id: null,
    total_indicacoes_diretas: 2,
    total_indicacoes_indiretas: 1,
    created_at: '2024-07-10T10:00:00Z',
    updated_at: '2024-11-01T10:00:00Z',
  },
  {
    id: MOCK_USER_12_ID,
    nome: 'Beatriz Monteiro',
    email: 'beatriz@monteiroinvest.com',
    telefone: '(41) 98765-1234',
    tipo: 'investidor',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'BEATRIZ2024',
    indicado_por_id: MOCK_USER_11_ID,
    total_indicacoes_diretas: 0,
    total_indicacoes_indiretas: 0,
    created_at: '2024-08-20T10:00:00Z',
    updated_at: '2024-11-15T10:00:00Z',
  },
  {
    id: MOCK_USER_13_ID,
    nome: 'Henrique Vasconcelos',
    email: 'henrique@hvcapital.com.br',
    telefone: '(61) 97654-3210',
    tipo: 'investidor',
    avatar_url: null,
    status: 'ativo',
    codigo_convite_proprio: 'HENRIQUE2024',
    indicado_por_id: null,
    total_indicacoes_diretas: 4,
    total_indicacoes_indiretas: 2,
    created_at: '2024-03-05T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
];

// ===================== PROFILE DETAILS =====================
export const mockProfileDetails = [
  {
    id: 'pd-001',
    user_id: MOCK_USER_ID,
    cpf: '123.456.789-00',
    data_nascimento: '1990-05-15',
    endereco_cep: '01310-100',
    endereco_logradouro: 'Av. Paulista',
    endereco_numero: '1000',
    endereco_complemento: 'Sala 1201',
    endereco_bairro: 'Bela Vista',
    endereco_cidade: 'São Paulo',
    endereco_uf: 'SP',
    profissao: 'Consultor Financeiro',
    empresa: 'Max Capital',
    cargo: 'Diretor',
  },
  {
    id: 'pd-002',
    user_id: MOCK_USER_4_ID,
    cpf: '987.654.321-00',
    data_nascimento: '1985-11-22',
    endereco_cep: '22041-080',
    endereco_logradouro: 'Rua Barata Ribeiro',
    endereco_numero: '350',
    endereco_complemento: 'Apto 802',
    endereco_bairro: 'Copacabana',
    endereco_cidade: 'Rio de Janeiro',
    endereco_uf: 'RJ',
    profissao: 'Assessora de Investimentos',
    empresa: 'BR Invest',
    cargo: 'Sócia',
  },
];

// ===================== EMPRESAS =====================
export const mockEmpresas = [
  {
    id: MOCK_EMPRESA_1_ID,
    nome: 'Tech Solutions Ltda',
    cnpj: '12.345.678/0001-90',
    nome_fantasia: 'TechSol',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    contato_email: 'contato@techsol.com',
    telefone: '(11) 3000-0001',
    endereco_cep: '01310-000',
    endereco_logradouro: 'Rua Augusta',
    endereco_numero: '500',
    endereco_complemento: null,
    endereco_bairro: 'Consolação',
    endereco_cidade: 'São Paulo',
    endereco_uf: 'SP',
    status_cadastro: 'completo',
    valor_operacao: 2500000,
    tipo_operacao: 'Investimento',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    criado_por_id: MOCK_USER_ID,
    responsavel: { nome: 'João Silva', email: 'joao@maxcapital.com.br' },
  },
  {
    id: MOCK_EMPRESA_2_ID,
    nome: 'Agro Brasil S.A.',
    cnpj: '98.765.432/0001-10',
    nome_fantasia: 'AgroBR',
    segmento: 'Agronegócio',
    responsavel_id: MOCK_USER_ID,
    contato_email: 'contato@agrobr.com',
    telefone: '(62) 3000-0002',
    endereco_cep: '74000-000',
    endereco_logradouro: 'Av. Goiás',
    endereco_numero: '1500',
    endereco_complemento: 'Andar 5',
    endereco_bairro: 'Centro',
    endereco_cidade: 'Goiânia',
    endereco_uf: 'GO',
    status_cadastro: 'completo',
    valor_operacao: 8000000,
    tipo_operacao: 'Crédito',
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    criado_por_id: MOCK_USER_ID,
    responsavel: { nome: 'João Silva', email: 'joao@maxcapital.com.br' },
  },
  {
    id: MOCK_EMPRESA_3_ID,
    nome: 'Energia Verde Ltda',
    cnpj: '11.222.333/0001-44',
    nome_fantasia: 'EcoEnergy',
    segmento: 'Energia',
    responsavel_id: MOCK_USER_2_ID,
    contato_email: 'contato@ecoenergy.com',
    telefone: '(21) 3000-0003',
    endereco_cep: '20040-020',
    endereco_logradouro: 'Av. Rio Branco',
    endereco_numero: '200',
    endereco_complemento: null,
    endereco_bairro: 'Centro',
    endereco_cidade: 'Rio de Janeiro',
    endereco_uf: 'RJ',
    status_cadastro: 'completo',
    valor_operacao: 5000000,
    tipo_operacao: 'Financiamento',
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    criado_por_id: MOCK_USER_2_ID,
    responsavel: { nome: 'Maria Santos', email: 'maria@empresa.com' },
  },
  {
    id: MOCK_EMPRESA_4_ID,
    nome: 'Construtora Horizonte S.A.',
    cnpj: '33.444.555/0001-66',
    nome_fantasia: 'Horizonte',
    segmento: 'Imobiliário',
    responsavel_id: MOCK_USER_4_ID,
    contato_email: 'contato@horizonte.com.br',
    telefone: '(21) 3100-4567',
    endereco_cep: '20031-170',
    endereco_logradouro: 'Rua da Assembleia',
    endereco_numero: '100',
    endereco_complemento: '12º andar',
    endereco_bairro: 'Centro',
    endereco_cidade: 'Rio de Janeiro',
    endereco_uf: 'RJ',
    status_cadastro: 'completo',
    valor_operacao: 15000000,
    tipo_operacao: 'Incorporação',
    created_at: '2024-04-10T10:00:00Z',
    updated_at: '2024-08-01T10:00:00Z',
    criado_por_id: MOCK_USER_4_ID,
    responsavel: { nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com' },
  },
  {
    id: MOCK_EMPRESA_5_ID,
    nome: 'FinBank Digital S.A.',
    cnpj: '44.555.666/0001-77',
    nome_fantasia: 'FinBank',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    contato_email: 'investors@finbank.com.br',
    telefone: '(11) 3200-8901',
    endereco_cep: '04543-011',
    endereco_logradouro: 'Av. Eng. Luís Carlos Berrini',
    endereco_numero: '1748',
    endereco_complemento: 'Conjunto 1801',
    endereco_bairro: 'Cidade Monções',
    endereco_cidade: 'São Paulo',
    endereco_uf: 'SP',
    status_cadastro: 'completo',
    valor_operacao: 12000000,
    tipo_operacao: 'Investimento',
    created_at: '2024-05-01T10:00:00Z',
    updated_at: '2024-09-01T10:00:00Z',
    criado_por_id: MOCK_USER_ID,
    responsavel: { nome: 'João Silva', email: 'joao@maxcapital.com.br' },
  },
  {
    id: MOCK_EMPRESA_6_ID,
    nome: 'Solar Norte Energias Ltda',
    cnpj: '55.666.777/0001-88',
    nome_fantasia: 'Solar Norte',
    segmento: 'Energia',
    responsavel_id: MOCK_USER_6_ID,
    contato_email: 'projetos@solarnorte.com',
    telefone: '(92) 3300-1234',
    endereco_cep: '69020-030',
    endereco_logradouro: 'Av. Eduardo Ribeiro',
    endereco_numero: '620',
    endereco_complemento: null,
    endereco_bairro: 'Centro',
    endereco_cidade: 'Manaus',
    endereco_uf: 'AM',
    status_cadastro: 'completo',
    valor_operacao: 22000000,
    tipo_operacao: 'Financiamento',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-09-15T10:00:00Z',
    criado_por_id: MOCK_USER_6_ID,
    responsavel: { nome: 'Fernanda Lima', email: 'fernanda@agro.com.br' },
  },
  {
    id: MOCK_EMPRESA_7_ID,
    nome: 'Grãos do Cerrado Ltda',
    cnpj: '66.777.888/0001-99',
    nome_fantasia: 'Cerrado Grãos',
    segmento: 'Agronegócio',
    responsavel_id: MOCK_USER_4_ID,
    contato_email: 'comercial@cerradograos.com.br',
    telefone: '(64) 3400-5678',
    endereco_cep: '75901-970',
    endereco_logradouro: 'Rua Bartolomeu Bueno',
    endereco_numero: '250',
    endereco_complemento: null,
    endereco_bairro: 'Setor Central',
    endereco_cidade: 'Rio Verde',
    endereco_uf: 'GO',
    status_cadastro: 'incompleto',
    valor_operacao: 6500000,
    tipo_operacao: 'Crédito',
    created_at: '2024-07-10T10:00:00Z',
    updated_at: '2024-10-01T10:00:00Z',
    criado_por_id: MOCK_USER_4_ID,
    responsavel: { nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com' },
  },
  {
    id: MOCK_EMPRESA_8_ID,
    nome: 'MedTech Saúde S.A.',
    cnpj: '77.888.999/0001-00',
    nome_fantasia: 'MedTech',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    contato_email: 'contato@medtech.com.br',
    telefone: '(11) 3500-9012',
    endereco_cep: '05407-002',
    endereco_logradouro: 'Rua Cardeal Arcoverde',
    endereco_numero: '2365',
    endereco_complemento: 'Sala 45',
    endereco_bairro: 'Pinheiros',
    endereco_cidade: 'São Paulo',
    endereco_uf: 'SP',
    status_cadastro: 'completo',
    valor_operacao: 4000000,
    tipo_operacao: 'Investimento',
    created_at: '2024-08-01T10:00:00Z',
    updated_at: '2024-10-15T10:00:00Z',
    criado_por_id: MOCK_USER_ID,
    responsavel: { nome: 'João Silva', email: 'joao@maxcapital.com.br' },
  },
  // New companies - recent with active exclusivity (no operations yet)
  {
    id: MOCK_EMPRESA_9_ID,
    nome: 'CloudPay Pagamentos S.A.',
    cnpj: '88.999.111/0001-22',
    nome_fantasia: 'CloudPay',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    contato_email: 'contato@cloudpay.com.br',
    telefone: '(11) 3600-1111',
    endereco_cep: '01310-100',
    endereco_logradouro: 'Av. Paulista',
    endereco_numero: '1000',
    endereco_complemento: 'Andar 15',
    endereco_bairro: 'Bela Vista',
    endereco_cidade: 'São Paulo',
    endereco_uf: 'SP',
    status_cadastro: 'completo',
    valor_operacao: 3000000,
    tipo_operacao: 'Investimento',
    data_exclusividade: '2025-12-01T10:00:00Z',
    created_at: '2025-12-01T10:00:00Z',
    updated_at: '2026-02-15T10:00:00Z',
    criado_por_id: MOCK_USER_ID,
    responsavel: { nome: 'João Silva', email: 'joao@maxcapital.com.br' },
  },
  {
    id: MOCK_EMPRESA_10_ID,
    nome: 'BioFarm Nutrição Animal Ltda',
    cnpj: '99.111.222/0001-33',
    nome_fantasia: 'BioFarm',
    segmento: 'Agronegócio',
    responsavel_id: MOCK_USER_4_ID,
    contato_email: 'vendas@biofarm.com.br',
    telefone: '(67) 3700-2222',
    endereco_cep: '79002-000',
    endereco_logradouro: 'Rua 14 de Julho',
    endereco_numero: '800',
    endereco_complemento: null,
    endereco_bairro: 'Centro',
    endereco_cidade: 'Campo Grande',
    endereco_uf: 'MS',
    status_cadastro: 'completo',
    valor_operacao: 5500000,
    tipo_operacao: 'Crédito',
    data_exclusividade: '2026-01-15T10:00:00Z',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
    criado_por_id: MOCK_USER_4_ID,
    responsavel: { nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com' },
  },
  {
    id: MOCK_EMPRESA_11_ID,
    nome: 'LogiTech Transportes S.A.',
    cnpj: '11.333.444/0001-55',
    nome_fantasia: 'LogiTech',
    segmento: 'Comercial',
    responsavel_id: MOCK_USER_2_ID,
    contato_email: 'operacoes@logitech-transp.com.br',
    telefone: '(41) 3800-3333',
    endereco_cep: '80010-000',
    endereco_logradouro: 'Rua XV de Novembro',
    endereco_numero: '300',
    endereco_complemento: null,
    endereco_bairro: 'Centro',
    endereco_cidade: 'Curitiba',
    endereco_uf: 'PR',
    status_cadastro: 'completo',
    valor_operacao: 7000000,
    tipo_operacao: 'Expansão',
    data_exclusividade: '2026-02-20T10:00:00Z',
    created_at: '2026-02-20T10:00:00Z',
    updated_at: '2026-03-04T10:00:00Z',
    criado_por_id: MOCK_USER_2_ID,
    responsavel: { nome: 'Maria Santos', email: 'maria@empresa.com' },
  },
  {
    id: MOCK_EMPRESA_12_ID,
    nome: 'Resíduo Zero Ambiental Ltda',
    cnpj: '22.444.555/0001-66',
    nome_fantasia: 'Resíduo Zero',
    segmento: 'Energia',
    responsavel_id: MOCK_USER_6_ID,
    contato_email: 'projetos@residuozero.com',
    telefone: '(85) 3900-4444',
    endereco_cep: '60060-000',
    endereco_logradouro: 'Av. Dom Manuel',
    endereco_numero: '150',
    endereco_complemento: 'Sala 201',
    endereco_bairro: 'Centro',
    endereco_cidade: 'Fortaleza',
    endereco_uf: 'CE',
    status_cadastro: 'incompleto',
    valor_operacao: 0,
    tipo_operacao: 'Financiamento',
    data_exclusividade: '2026-03-01T10:00:00Z',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-04T10:00:00Z',
    criado_por_id: MOCK_USER_6_ID,
    responsavel: { nome: 'Fernanda Lima', email: 'fernanda@agro.com.br' },
  },
];

// ===================== OPERAÇÕES =====================
export const mockOperacoes = [
  {
    id: MOCK_OP_1_ID,
    numero_funil: 'OP-2024-001',
    empresa_id: MOCK_EMPRESA_1_ID,
    etapa_atual: 'Matchmaking',
    sub_etapa: null,
    valor_investimento: 2500000,
    tipo_capital: 'Captação',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    office: 'Sudeste',
    lead_tag: 'quente',
    status_exclusividade: 'Ativo',
    data_exclusividade: '2024-12-31',
    dias_na_etapa: 5,
    dias_desde_atualizacao: 2,
    created_at: '2024-05-01T10:00:00Z',
    ultima_movimentacao: '2024-06-01T10:00:00Z',
    observacoes: 'Empresa com alto potencial de crescimento',
    empresa: { id: MOCK_EMPRESA_1_ID, nome: 'Tech Solutions Ltda', cnpj: '12.345.678/0001-90', segmento: 'Startups' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: MOCK_OP_2_ID,
    numero_funil: 'OP-2024-002',
    empresa_id: MOCK_EMPRESA_2_ID,
    etapa_atual: 'Comitê',
    sub_etapa: null,
    valor_investimento: 8000000,
    tipo_capital: 'Investimento',
    segmento: 'Agronegócio',
    responsavel_id: MOCK_USER_ID,
    office: 'Centro-Oeste',
    lead_tag: 'morno',
    status_exclusividade: 'Sem exclusividade',
    data_exclusividade: null,
    dias_na_etapa: 12,
    dias_desde_atualizacao: 3,
    created_at: '2024-04-15T10:00:00Z',
    ultima_movimentacao: '2024-05-28T10:00:00Z',
    observacoes: 'Aguardando documentação complementar',
    empresa: { id: MOCK_EMPRESA_2_ID, nome: 'Agro Brasil S.A.', cnpj: '98.765.432/0001-10', segmento: 'Agronegócio' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: MOCK_OP_3_ID,
    numero_funil: 'OP-2024-003',
    empresa_id: MOCK_EMPRESA_3_ID,
    etapa_atual: 'Comercial',
    sub_etapa: null,
    valor_investimento: 5000000,
    tipo_capital: 'Híbrido',
    segmento: 'Energia',
    responsavel_id: MOCK_USER_ID,
    office: 'Sudeste',
    lead_tag: 'frio',
    status_exclusividade: 'Ativo',
    data_exclusividade: '2025-06-30',
    dias_na_etapa: 20,
    dias_desde_atualizacao: 7,
    created_at: '2024-03-20T10:00:00Z',
    ultima_movimentacao: '2024-05-20T10:00:00Z',
    observacoes: null,
    empresa: { id: MOCK_EMPRESA_3_ID, nome: 'Energia Verde Ltda', cnpj: '11.222.333/0001-44', segmento: 'Energia' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: MOCK_OP_4_ID,
    numero_funil: 'OP-2024-004',
    empresa_id: MOCK_EMPRESA_1_ID,
    etapa_atual: 'Concluído',
    sub_etapa: null,
    valor_investimento: 1500000,
    tipo_capital: 'Captação',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    office: 'Sudeste',
    lead_tag: 'convertido',
    status_exclusividade: 'Vencido',
    data_exclusividade: '2024-03-31',
    dias_na_etapa: 0,
    dias_desde_atualizacao: 30,
    created_at: '2024-01-10T10:00:00Z',
    ultima_movimentacao: '2024-04-01T10:00:00Z',
    observacoes: 'Operação concluída com sucesso',
    empresa: { id: MOCK_EMPRESA_1_ID, nome: 'Tech Solutions Ltda', cnpj: '12.345.678/0001-90', segmento: 'Startups' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: MOCK_OP_5_ID,
    numero_funil: 'OP-2024-005',
    empresa_id: MOCK_EMPRESA_2_ID,
    etapa_atual: 'Matchmaking',
    sub_etapa: null,
    valor_investimento: 3000000,
    tipo_capital: 'Investimento',
    segmento: 'Agronegócio',
    responsavel_id: MOCK_USER_ID,
    office: 'Centro-Oeste',
    lead_tag: 'quente',
    status_exclusividade: 'Ativo',
    data_exclusividade: '2025-01-31',
    dias_na_etapa: 8,
    dias_desde_atualizacao: 1,
    created_at: '2024-05-15T10:00:00Z',
    ultima_movimentacao: '2024-06-02T10:00:00Z',
    observacoes: 'Buscando investidores compatíveis',
    empresa: { id: MOCK_EMPRESA_2_ID, nome: 'Agro Brasil S.A.', cnpj: '98.765.432/0001-10', segmento: 'Agronegócio' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: MOCK_OP_6_ID,
    numero_funil: 'OP-2024-006',
    empresa_id: MOCK_EMPRESA_4_ID,
    etapa_atual: 'Estruturação',
    sub_etapa: null,
    valor_investimento: 15000000,
    tipo_capital: 'Captação',
    segmento: 'Imobiliário',
    responsavel_id: MOCK_USER_4_ID,
    office: 'Sudeste',
    lead_tag: 'quente',
    status_exclusividade: 'Ativo',
    data_exclusividade: '2025-12-31',
    dias_na_etapa: 3,
    dias_desde_atualizacao: 1,
    created_at: '2024-07-01T10:00:00Z',
    ultima_movimentacao: '2024-10-10T10:00:00Z',
    observacoes: 'Empreendimento residencial de alto padrão em Copacabana',
    empresa: { id: MOCK_EMPRESA_4_ID, nome: 'Construtora Horizonte S.A.', cnpj: '33.444.555/0001-66', segmento: 'Imobiliário' },
    responsavel: { id: MOCK_USER_4_ID, nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com', avatar_url: null },
  },
  {
    id: MOCK_OP_7_ID,
    numero_funil: 'OP-2024-007',
    empresa_id: MOCK_EMPRESA_5_ID,
    etapa_atual: 'Matchmaking',
    sub_etapa: null,
    valor_investimento: 12000000,
    tipo_capital: 'Investimento',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    office: 'Sudeste',
    lead_tag: 'quente',
    status_exclusividade: 'Ativo',
    data_exclusividade: '2025-06-30',
    dias_na_etapa: 15,
    dias_desde_atualizacao: 2,
    created_at: '2024-06-15T10:00:00Z',
    ultima_movimentacao: '2024-10-05T10:00:00Z',
    observacoes: 'Fintech com crescimento de 300% a.a., negociação de valuation',
    empresa: { id: MOCK_EMPRESA_5_ID, nome: 'FinBank Digital S.A.', cnpj: '44.555.666/0001-77', segmento: 'Startups' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: MOCK_OP_8_ID,
    numero_funil: 'OP-2024-008',
    empresa_id: MOCK_EMPRESA_6_ID,
    etapa_atual: 'Matchmaking',
    sub_etapa: null,
    valor_investimento: 22000000,
    tipo_capital: 'Híbrido',
    segmento: 'Energia',
    responsavel_id: MOCK_USER_6_ID,
    office: 'Norte',
    lead_tag: 'convertido',
    status_exclusividade: 'Ativo',
    data_exclusividade: '2026-01-31',
    dias_na_etapa: 45,
    dias_desde_atualizacao: 5,
    created_at: '2024-05-20T10:00:00Z',
    ultima_movimentacao: '2024-09-20T10:00:00Z',
    observacoes: 'Usina solar com contrato de compra de energia de 20 anos',
    empresa: { id: MOCK_EMPRESA_6_ID, nome: 'Solar Norte Energias Ltda', cnpj: '55.666.777/0001-88', segmento: 'Energia' },
    responsavel: { id: MOCK_USER_6_ID, nome: 'Fernanda Lima', email: 'fernanda@agro.com.br', avatar_url: null },
  },
  {
    id: MOCK_OP_9_ID,
    numero_funil: 'OP-2024-009',
    empresa_id: MOCK_EMPRESA_7_ID,
    etapa_atual: 'Prospecto',
    sub_etapa: null,
    valor_investimento: 6500000,
    tipo_capital: 'Captação',
    segmento: 'Agronegócio',
    responsavel_id: MOCK_USER_4_ID,
    office: 'Centro-Oeste',
    lead_tag: 'morno',
    status_exclusividade: 'Sem exclusividade',
    data_exclusividade: null,
    dias_na_etapa: 10,
    dias_desde_atualizacao: 4,
    created_at: '2024-08-01T10:00:00Z',
    ultima_movimentacao: '2024-10-08T10:00:00Z',
    observacoes: 'Cadastro incompleto — pendente documentação societária',
    empresa: { id: MOCK_EMPRESA_7_ID, nome: 'Grãos do Cerrado Ltda', cnpj: '66.777.888/0001-99', segmento: 'Agronegócio' },
    responsavel: { id: MOCK_USER_4_ID, nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com', avatar_url: null },
  },
  {
    id: MOCK_OP_10_ID,
    numero_funil: 'OP-2024-010',
    empresa_id: MOCK_EMPRESA_8_ID,
    etapa_atual: 'Matchmaking',
    sub_etapa: null,
    valor_investimento: 4000000,
    tipo_capital: 'Investimento',
    segmento: 'Startups',
    responsavel_id: MOCK_USER_ID,
    office: 'Sudeste',
    lead_tag: 'quente',
    status_exclusividade: 'Ativo',
    data_exclusividade: '2025-09-30',
    dias_na_etapa: 6,
    dias_desde_atualizacao: 1,
    created_at: '2024-09-01T10:00:00Z',
    ultima_movimentacao: '2024-10-12T10:00:00Z',
    observacoes: 'HealthTech com patentes registradas, análise de due diligence em andamento',
    empresa: { id: MOCK_EMPRESA_8_ID, nome: 'MedTech Saúde S.A.', cnpj: '77.888.999/0001-00', segmento: 'Startups' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: 'mock-op-draft-001',
    numero_funil: 'OP-2025-011',
    empresa_id: MOCK_EMPRESA_3_ID,
    etapa_atual: 'Prospecto',
    sub_etapa: null,
    valor_investimento: 3200000,
    tipo_capital: 'Captação',
    segmento: 'Imobiliário',
    responsavel_id: MOCK_USER_ID,
    office: 'Sudeste',
    lead_tag: 'frio',
    status_exclusividade: 'Sem exclusividade',
    data_exclusividade: null,
    dias_na_etapa: 2,
    dias_desde_atualizacao: 0,
    created_at: '2025-03-03T14:00:00Z',
    ultima_movimentacao: '2025-03-05T10:00:00Z',
    observacoes: JSON.stringify({
      _draft: true,
      _progress: 39,
      formData: {
        setor: 'imobiliario',
        segmento: 'Imobiliário',
        nomeProjeto: 'Residencial Vila Nova',
        cnpj: '33.444.555/0001-66',
        investimentoNecessario: '3.200.000,00',
        valorTotal: '3.200.000,00',
        cidade: 'Campinas',
        uf: 'SP',
        cep: '13070-000',
      },
    }),
    empresa: { id: MOCK_EMPRESA_3_ID, nome: 'Residencial Vila Nova', cnpj: '33.444.555/0001-66', segmento: 'Imobiliário' },
    responsavel: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
];

// ===================== MOVIMENTAÇÕES HISTÓRICO =====================
export const mockMovimentacoesHistorico = [
  {
    id: 'hist-001',
    operacao_id: MOCK_OP_4_ID,
    usuario_id: MOCK_USER_ID,
    etapa_anterior: 'Negociação',
    sub_etapa_anterior: null,
    etapa_nova: 'Concluído',
    sub_etapa_nova: null,
    data_hora: '2024-04-01T10:00:00Z',
    observacoes: 'Operação finalizada com sucesso',
    usuario: { nome: 'João Silva', avatar_url: null },
  },
  {
    id: 'hist-002',
    operacao_id: MOCK_OP_1_ID,
    usuario_id: MOCK_USER_ID,
    etapa_anterior: 'Prospecto',
    sub_etapa_anterior: null,
    etapa_nova: 'Comitê',
    sub_etapa_nova: null,
    data_hora: '2024-05-15T10:00:00Z',
    observacoes: 'Aprovado para análise do comitê',
    usuario: { nome: 'João Silva', avatar_url: null },
  },
  {
    id: 'hist-003',
    operacao_id: MOCK_OP_7_ID,
    usuario_id: MOCK_USER_ID,
    etapa_anterior: 'Estruturação',
    sub_etapa_anterior: null,
    etapa_nova: 'Negociação',
    sub_etapa_nova: null,
    data_hora: '2024-09-20T10:00:00Z',
    observacoes: 'Due diligence concluída, iniciando negociação de termos',
    usuario: { nome: 'João Silva', avatar_url: null },
  },
  {
    id: 'hist-004',
    operacao_id: MOCK_OP_8_ID,
    usuario_id: MOCK_USER_6_ID,
    etapa_anterior: 'Matchmaking',
    sub_etapa_anterior: null,
    etapa_nova: 'Cliente Ativo',
    sub_etapa_nova: null,
    data_hora: '2024-08-15T10:00:00Z',
    observacoes: 'Contrato assinado com investidor âncora',
    usuario: { nome: 'Fernanda Lima', avatar_url: null },
  },
];

// ===================== MEMBROS REDE =====================
export const mockMembrosRede = [
  {
    id: 'membro-001',
    usuario_id: MOCK_USER_2_ID,
    indicacao: 'Direta',
    nivel: 'Nível 1',
    numero_negocios: 3,
    valor_total: 5000000,
    ultimo_negocio: '2024-05-15T10:00:00Z',
    status: 'Ativo',
    created_at: '2024-02-20T10:00:00Z',
    usuario: { id: MOCK_USER_2_ID, nome: 'Maria Santos', email: 'maria@empresa.com', telefone: '(11) 99999-0002', avatar_url: null },
  },
  {
    id: 'membro-002',
    usuario_id: MOCK_USER_3_ID,
    indicacao: 'Direta',
    nivel: 'Nível 1',
    numero_negocios: 1,
    valor_total: 1500000,
    ultimo_negocio: '2024-04-01T10:00:00Z',
    status: 'Ativo',
    created_at: '2024-03-10T10:00:00Z',
    usuario: { id: MOCK_USER_3_ID, nome: 'Carlos Oliveira', email: 'carlos@investidor.com', telefone: '(11) 99999-0003', avatar_url: null },
  },
  {
    id: 'membro-003',
    usuario_id: MOCK_USER_4_ID,
    indicacao: 'Direta',
    nivel: 'Nível 1',
    numero_negocios: 5,
    valor_total: 21500000,
    ultimo_negocio: '2024-10-10T10:00:00Z',
    status: 'Ativo',
    created_at: '2024-03-15T10:00:00Z',
    usuario: { id: MOCK_USER_4_ID, nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com', telefone: '(21) 98888-1234', avatar_url: null },
  },
  {
    id: 'membro-004',
    usuario_id: MOCK_USER_5_ID,
    indicacao: 'Indireta',
    nivel: 'Nível 2',
    numero_negocios: 2,
    valor_total: 3000000,
    ultimo_negocio: '2024-08-20T10:00:00Z',
    status: 'Ativo',
    created_at: '2024-04-01T10:00:00Z',
    usuario: { id: MOCK_USER_5_ID, nome: 'Ricardo Mendes', email: 'ricardo@investimentos.com', telefone: '(31) 97777-5678', avatar_url: null },
  },
  {
    id: 'membro-005',
    usuario_id: MOCK_USER_6_ID,
    indicacao: 'Indireta',
    nivel: 'Nível 2',
    numero_negocios: 1,
    valor_total: 22000000,
    ultimo_negocio: '2024-09-20T10:00:00Z',
    status: 'Ativo',
    created_at: '2024-04-20T10:00:00Z',
    usuario: { id: MOCK_USER_6_ID, nome: 'Fernanda Lima', email: 'fernanda@agro.com.br', telefone: '(62) 96666-9012', avatar_url: null },
  },
];

// ===================== INDICAÇÕES =====================
export const mockIndicacoes = [
  {
    id: 'ind-001',
    indicador_id: MOCK_USER_ID,
    indicado_id: MOCK_USER_2_ID,
    nivel_indicacao: 1,
    indicacao_pai_id: null,
    codigo_convite: 'JOAO2024',
    status: 'ativo',
    data_indicacao: '2024-02-20T10:00:00Z',
    indicado: { id: MOCK_USER_2_ID, nome: 'Maria Santos', email: 'maria@empresa.com', avatar_url: null, created_at: '2024-02-20T10:00:00Z' },
  },
  {
    id: 'ind-002',
    indicador_id: MOCK_USER_ID,
    indicado_id: MOCK_USER_3_ID,
    nivel_indicacao: 1,
    indicacao_pai_id: null,
    codigo_convite: 'JOAO2024',
    status: 'ativo',
    data_indicacao: '2024-03-10T10:00:00Z',
    indicado: { id: MOCK_USER_3_ID, nome: 'Carlos Oliveira', email: 'carlos@investidor.com', avatar_url: null, created_at: '2024-03-10T10:00:00Z' },
  },
  {
    id: 'ind-003',
    indicador_id: MOCK_USER_ID,
    indicado_id: MOCK_USER_4_ID,
    nivel_indicacao: 1,
    indicacao_pai_id: null,
    codigo_convite: 'JOAO2024',
    status: 'ativo',
    data_indicacao: '2024-03-15T10:00:00Z',
    indicado: { id: MOCK_USER_4_ID, nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com', avatar_url: null, created_at: '2024-03-15T10:00:00Z' },
  },
  {
    id: 'ind-004',
    indicador_id: MOCK_USER_4_ID,
    indicado_id: MOCK_USER_5_ID,
    nivel_indicacao: 2,
    indicacao_pai_id: 'ind-003',
    codigo_convite: 'ANA2024',
    status: 'ativo',
    data_indicacao: '2024-04-01T10:00:00Z',
    indicado: { id: MOCK_USER_5_ID, nome: 'Ricardo Mendes', email: 'ricardo@investimentos.com', avatar_url: null, created_at: '2024-04-01T10:00:00Z' },
  },
  {
    id: 'ind-005',
    indicador_id: MOCK_USER_4_ID,
    indicado_id: MOCK_USER_8_ID,
    nivel_indicacao: 2,
    indicacao_pai_id: 'ind-003',
    codigo_convite: 'ANA2024',
    status: 'pendente',
    data_indicacao: '2024-09-01T10:00:00Z',
    indicado: { id: MOCK_USER_8_ID, nome: 'Juliana Rocha', email: 'juliana@parceiro.com', avatar_url: null, created_at: '2024-09-01T10:00:00Z' },
  },
];

// ===================== TESES DE INVESTIMENTO =====================
export const mockTesesInvestimento = [
  {
    id: 'tese-001',
    titulo: 'Startups de Tecnologia - Série A',
    descricao: 'Investimentos em startups de tecnologia em fase de crescimento, buscando escalar operações e expandir mercado.',
    tipo: 'Equity',
    categoria: 'Venture Capital',
    valor_min: 1000000,
    valor_max: 10000000,
    ativo: true,
    created_at: '2024-01-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    setores: ['Tecnologia', 'SaaS', 'Fintech'],
    modelo_negocio: 'B2B',
    fase_investimento: 'Série A',
    tese_quente: true,
    investidor_id: MOCK_USER_ID,
  },
  {
    id: 'tese-002',
    titulo: 'Agronegócio Sustentável',
    descricao: 'Financiamento para projetos agro com práticas sustentáveis e certificações ambientais.',
    tipo: 'Crédito',
    categoria: 'Agro',
    valor_min: 5000000,
    valor_max: 50000000,
    ativo: true,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    setores: ['Agronegócio', 'Sustentabilidade'],
    modelo_negocio: 'B2B',
    fase_investimento: 'Growth',
    tese_quente: false,
    investidor_id: MOCK_USER_11_ID,
  },
  {
    id: 'tese-003',
    titulo: 'Energia Renovável',
    descricao: 'Investimentos em projetos de energia solar, eólica e biomassa com retorno previsível.',
    tipo: 'Project Finance',
    categoria: 'Infraestrutura',
    valor_min: 10000000,
    valor_max: 100000000,
    ativo: true,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    setores: ['Energia', 'Infraestrutura'],
    modelo_negocio: 'B2G',
    fase_investimento: 'Greenfield',
    tese_quente: true,
    investidor_id: MOCK_USER_5_ID,
  },
  {
    id: 'tese-004',
    titulo: 'Real Estate Residencial Premium',
    descricao: 'Incorporações residenciais de alto padrão em capitais com alta demanda reprimida e VGV acima de R$ 50M.',
    tipo: 'Equity',
    categoria: 'Imobiliário',
    valor_min: 10000000,
    valor_max: 80000000,
    ativo: true,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-08-01T10:00:00Z',
    setores: ['Imobiliário', 'Construção Civil'],
    modelo_negocio: 'B2C',
    fase_investimento: 'Development',
    tese_quente: true,
    investidor_id: MOCK_USER_12_ID,
  },
  {
    id: 'tese-005',
    titulo: 'HealthTech & BioTech',
    descricao: 'Startups de saúde digital, telemedicina, dispositivos médicos e biotecnologia com propriedade intelectual registrada.',
    tipo: 'Equity',
    categoria: 'Venture Capital',
    valor_min: 2000000,
    valor_max: 15000000,
    ativo: true,
    created_at: '2024-05-01T10:00:00Z',
    updated_at: '2024-09-01T10:00:00Z',
    setores: ['Saúde', 'Tecnologia', 'Biotecnologia'],
    modelo_negocio: 'B2B2C',
    fase_investimento: 'Seed / Série A',
    tese_quente: false,
    investidor_id: MOCK_USER_10_ID,
  },
  {
    id: 'tese-006',
    titulo: 'Crédito Estruturado - Middle Market',
    descricao: 'Operações de crédito para empresas de médio porte com faturamento entre R$ 50M e R$ 500M, com garantias reais.',
    tipo: 'Crédito',
    categoria: 'Crédito Corporativo',
    valor_min: 5000000,
    valor_max: 30000000,
    ativo: true,
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-10-01T10:00:00Z',
    setores: ['Indústria', 'Comércio', 'Serviços'],
    modelo_negocio: 'B2B',
    fase_investimento: 'Growth',
    tese_quente: false,
    investidor_id: MOCK_USER_3_ID,
  },
  {
    id: 'tese-007',
    titulo: 'Infraestrutura & Saneamento',
    descricao: 'PPPs e concessões de saneamento básico, rodovias e infraestrutura urbana com contratos de longo prazo.',
    tipo: 'Project Finance',
    categoria: 'Infraestrutura',
    valor_min: 50000000,
    valor_max: 500000000,
    ativo: true,
    created_at: '2024-07-01T10:00:00Z',
    updated_at: '2024-10-15T10:00:00Z',
    setores: ['Saneamento', 'Infraestrutura', 'Governo'],
    modelo_negocio: 'B2G',
    fase_investimento: 'Greenfield / Brownfield',
    tese_quente: true,
    investidor_id: MOCK_USER_13_ID,
  },
  {
    id: 'tese-008',
    titulo: 'Logística & Supply Chain',
    descricao: 'Investimentos em empresas de logística integrada, last-mile delivery e tecnologia para cadeia de suprimentos.',
    tipo: 'Equity',
    categoria: 'Venture Capital',
    valor_min: 3000000,
    valor_max: 20000000,
    ativo: true,
    created_at: '2024-08-01T10:00:00Z',
    updated_at: '2024-11-01T10:00:00Z',
    setores: ['Logística', 'Tecnologia', 'E-commerce'],
    modelo_negocio: 'B2B',
    fase_investimento: 'Série A / B',
    tese_quente: true,
    investidor_id: MOCK_USER_11_ID,
  },
  {
    id: 'tese-009',
    titulo: 'EdTech & Educação Corporativa',
    descricao: 'Plataformas de educação digital, treinamento corporativo e soluções de aprendizado adaptativo com IA.',
    tipo: 'Equity',
    categoria: 'Venture Capital',
    valor_min: 1000000,
    valor_max: 8000000,
    ativo: true,
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
    setores: ['Educação', 'Tecnologia'],
    modelo_negocio: 'B2B2C',
    fase_investimento: 'Seed',
    tese_quente: false,
    investidor_id: MOCK_USER_13_ID,
  },
  {
    id: 'tese-010',
    titulo: 'Varejo & Franquias Premium',
    descricao: 'Expansão de redes de franquias de alto padrão com ticket médio elevado e forte presença em shopping centers.',
    tipo: 'Equity',
    categoria: 'Private Equity',
    valor_min: 5000000,
    valor_max: 40000000,
    ativo: true,
    created_at: '2024-10-01T10:00:00Z',
    updated_at: '2025-01-01T10:00:00Z',
    setores: ['Varejo', 'Franquias', 'Consumo'],
    modelo_negocio: 'B2C',
    fase_investimento: 'Growth',
    tese_quente: true,
    investidor_id: MOCK_USER_12_ID,
  },
];

// ===================== OPORTUNIDADES DE INVESTIMENTO =====================
export const mockOportunidadesInvestimento = [
  {
    id: 'oport-001',
    nome: 'Rodada Série A - TechSol',
    descricao: 'Oportunidade de investimento na rodada Série A da Tech Solutions, líder em automação industrial com IA.',
    tipo: 'Equity',
    segmento: 'Tecnologia',
    instrumento: 'Nota Comercial',
    rentabilidade: 25.0,
    investimento_minimo: 100000,
    prazo: 36,
    pagamento: 'No vencimento',
    status: 'aberta',
    captado: 2500000,
    alvo_minimo: 3000000,
    alvo_maximo: 5000000,
    investidores: 8,
    data_inicio: '2024-05-01',
    data_fim: '2025-03-31',
    garantia: 'Participação societária com tag-along de 100%',
    devedora: 'Tech Solutions S.A.',
    amortizacao: 'Bullet',
    risco: 'Alto',
    destaque: true,
    image_url: '',
    empresa: { nome: 'Tech Solutions S.A.', descricao: 'Empresa de automação industrial com IA, atendendo +200 clientes.', experiencia: '8 anos no mercado', projetos: 45, unidades_entregues: 0 },
    financeiro: { faturamento_2023: 12000000, faturamento_2024: 18000000, faturamento_2025: 28000000, faturamento_2026: 42000000, ebitda_2023: 2400000, ebitda_2024: 4500000, ebitda_2025: 8400000, ebitda_2026: 14700000 },
    documentos: [],
    operacao_origem_id: MOCK_OP_1_ID,
    created_at: '2024-05-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'oport-002',
    nome: 'CRA Agro Brasil - Safra 2025',
    descricao: 'Certificado de Recebíveis do Agronegócio para financiamento da safra de soja e milho no MT.',
    tipo: 'Dívida',
    segmento: 'Agronegócio',
    instrumento: 'CRA',
    rentabilidade: 14.5,
    investimento_minimo: 500000,
    prazo: 24,
    pagamento: 'Semestral',
    status: 'aberta',
    captado: 15000000,
    alvo_minimo: 15000000,
    alvo_maximo: 20000000,
    investidores: 12,
    data_inicio: '2024-04-01',
    data_fim: '2025-06-30',
    garantia: 'Penhor de safra + alienação fiduciária de imóveis rurais avaliados em R$ 45M',
    devedora: 'Agro Brasil Participações Ltda.',
    amortizacao: 'SAC',
    risco: 'Baixo',
    destaque: false,
    image_url: '',
    empresa: { nome: 'Agro Brasil Participações', descricao: 'Grupo com 120 mil hectares de área plantada no Mato Grosso.', experiencia: '25 anos no agronegócio', projetos: 18, unidades_entregues: 0 },
    financeiro: { faturamento_2023: 280000000, faturamento_2024: 320000000, faturamento_2025: 350000000, faturamento_2026: 400000000, ebitda_2023: 56000000, ebitda_2024: 70000000, ebitda_2025: 80000000, ebitda_2026: 96000000 },
    documentos: [],
    operacao_origem_id: MOCK_OP_5_ID,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'oport-003',
    nome: 'Debênture Solar Norte - Usina Manaus I',
    descricao: 'Debênture incentivada para financiamento de usina solar de 50MW em Manaus com contrato PPA de 20 anos.',
    tipo: 'Dívida',
    segmento: 'Energia',
    instrumento: 'Debênture',
    rentabilidade: 16.8,
    investimento_minimo: 250000,
    prazo: 60,
    pagamento: 'Trimestral',
    status: 'aberta',
    captado: 18500000,
    alvo_minimo: 18000000,
    alvo_maximo: 22000000,
    investidores: 15,
    data_inicio: '2024-06-15',
    data_fim: '2025-04-30',
    garantia: 'Cessão fiduciária de recebíveis do PPA + seguro performance',
    devedora: 'Solar Norte Energia S.A.',
    amortizacao: 'Price',
    risco: 'Médio',
    destaque: true,
    image_url: '',
    empresa: { nome: 'Solar Norte Energia S.A.', descricao: 'Empresa do grupo Norte Energia focada em geração fotovoltaica na região amazônica.', experiencia: '12 anos em energia renovável', projetos: 8, unidades_entregues: 5 },
    financeiro: { faturamento_2023: 45000000, faturamento_2024: 52000000, faturamento_2025: 68000000, faturamento_2026: 85000000, ebitda_2023: 18000000, ebitda_2024: 22000000, ebitda_2025: 30000000, ebitda_2026: 40000000 },
    documentos: [],
    operacao_origem_id: MOCK_OP_8_ID,
    created_at: '2024-06-15T10:00:00Z',
    updated_at: '2024-10-01T10:00:00Z',
  },
  {
    id: 'oport-004',
    nome: 'Equity Horizonte - Residencial Copacabana',
    descricao: 'Participação no empreendimento residencial de alto padrão com VGV projetado de R$ 120M.',
    tipo: 'Equity',
    segmento: 'Imobiliário',
    instrumento: 'CRI',
    rentabilidade: 22.0,
    investimento_minimo: 500000,
    prazo: 48,
    pagamento: 'Semestral',
    status: 'aberta',
    captado: 6000000,
    alvo_minimo: 10000000,
    alvo_maximo: 15000000,
    investidores: 5,
    data_inicio: '2024-07-10',
    data_fim: '2025-08-31',
    garantia: 'Alienação fiduciária do terreno + cessão de recebíveis das unidades',
    devedora: 'Horizonte Incorporações S.A.',
    amortizacao: 'Bullet',
    risco: 'Médio',
    destaque: false,
    image_url: '',
    empresa: { nome: 'Horizonte Incorporações', descricao: 'Incorporadora premium com foco em empreendimentos de alto padrão no Rio de Janeiro.', experiencia: '30 anos no mercado imobiliário', projetos: 42, unidades_entregues: 3200 },
    financeiro: { faturamento_2023: 180000000, faturamento_2024: 220000000, faturamento_2025: 260000000, faturamento_2026: 310000000, ebitda_2023: 36000000, ebitda_2024: 48000000, ebitda_2025: 62000000, ebitda_2026: 78000000 },
    documentos: [],
    operacao_origem_id: MOCK_OP_6_ID,
    created_at: '2024-07-10T10:00:00Z',
    updated_at: '2024-10-05T10:00:00Z',
  },
  {
    id: 'oport-005',
    nome: 'Série Seed - FinBank Digital',
    descricao: 'Rodada seed para expansão da plataforma de banking-as-a-service com crescimento de 300% a.a.',
    tipo: 'Equity',
    segmento: 'Tecnologia',
    instrumento: 'Nota Comercial',
    rentabilidade: 0,
    investimento_minimo: 200000,
    prazo: 0,
    pagamento: 'No vencimento',
    status: 'aberta',
    captado: 9500000,
    alvo_minimo: 8000000,
    alvo_maximo: 12000000,
    investidores: 18,
    data_inicio: '2024-08-01',
    data_fim: '2025-05-31',
    garantia: 'Participação societária com direitos de preferência',
    devedora: 'FinBank Digital Ltda.',
    amortizacao: 'N/A',
    risco: 'Alto',
    destaque: true,
    image_url: '',
    empresa: { nome: 'FinBank Digital', descricao: 'Fintech de banking-as-a-service com +50 clientes institucionais e 2M de contas.', experiencia: '4 anos de operação', projetos: 3, unidades_entregues: 0 },
    financeiro: { faturamento_2023: 8000000, faturamento_2024: 24000000, faturamento_2025: 72000000, faturamento_2026: 150000000, ebitda_2023: -2000000, ebitda_2024: 1200000, ebitda_2025: 14400000, ebitda_2026: 37500000 },
    documentos: [],
    operacao_origem_id: MOCK_OP_7_ID,
    created_at: '2024-08-01T10:00:00Z',
    updated_at: '2024-10-10T10:00:00Z',
  },
  {
    id: 'oport-006',
    nome: 'CRI Horizonte - Lote Comercial Barra',
    descricao: 'Certificado de Recebíveis Imobiliários para loteamento comercial na Barra da Tijuca.',
    tipo: 'Dívida',
    segmento: 'Imobiliário',
    instrumento: 'CRI',
    rentabilidade: 13.2,
    investimento_minimo: 100000,
    prazo: 18,
    pagamento: 'Mensal',
    status: 'captada',
    captado: 8000000,
    alvo_minimo: 6000000,
    alvo_maximo: 8000000,
    investidores: 22,
    data_inicio: '2024-03-01',
    data_fim: '2024-12-31',
    garantia: 'Alienação fiduciária dos lotes + fiança corporativa',
    devedora: 'Horizonte Loteamentos S.A.',
    amortizacao: 'SAC',
    risco: 'Baixo',
    destaque: false,
    image_url: '',
    empresa: { nome: 'Horizonte Loteamentos', descricao: 'Braço de loteamentos do grupo Horizonte com 15 empreendimentos entregues.', experiencia: '20 anos de mercado', projetos: 15, unidades_entregues: 4500 },
    financeiro: { faturamento_2023: 95000000, faturamento_2024: 110000000, faturamento_2025: 130000000, faturamento_2026: 155000000, ebitda_2023: 23000000, ebitda_2024: 28000000, ebitda_2025: 35000000, ebitda_2026: 42000000 },
    documentos: [],
    operacao_origem_id: MOCK_OP_6_ID,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-09-15T10:00:00Z',
  },
  {
    id: 'oport-007',
    nome: 'MedTech - Rodada Pre-Seed',
    descricao: 'Investimento em HealthTech focada em diagnóstico por IA com 3 patentes registradas.',
    tipo: 'Equity',
    segmento: 'Startups',
    instrumento: 'Nota Comercial',
    rentabilidade: 0,
    investimento_minimo: 50000,
    prazo: 0,
    pagamento: 'No vencimento',
    status: 'aberta',
    captado: 1200000,
    alvo_minimo: 2000000,
    alvo_maximo: 4000000,
    investidores: 6,
    data_inicio: '2024-09-01',
    data_fim: '2025-09-30',
    garantia: 'Equity direto com cláusula anti-diluição',
    devedora: 'MedTech Diagnósticos S.A.',
    amortizacao: 'N/A',
    risco: 'Alto',
    destaque: false,
    image_url: '',
    empresa: { nome: 'MedTech Diagnósticos', descricao: 'HealthTech de diagnóstico por IA com 3 patentes e parcerias com hospitais de referência.', experiencia: '3 anos de pesquisa e desenvolvimento', projetos: 2, unidades_entregues: 0 },
    financeiro: { faturamento_2023: 500000, faturamento_2024: 2000000, faturamento_2025: 8000000, faturamento_2026: 25000000, ebitda_2023: -1500000, ebitda_2024: -800000, ebitda_2025: 1600000, ebitda_2026: 7500000 },
    documentos: [],
    operacao_origem_id: MOCK_OP_10_ID,
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2024-10-12T10:00:00Z',
  },
];

// ===================== CURSOS =====================
export const mockCursos = [
  {
    id: 'curso-001',
    titulo: 'Introdução ao Mercado de Capitais',
    categoria: 'Fundamentos',
    duracao: '2h30',
    descricao: 'Curso introdutório sobre mercado de capitais, tipos de investimento e regulamentação.',
    video_url: null,
    ordem: 1,
    created_at: '2024-01-01T10:00:00Z',
  },
  {
    id: 'curso-002',
    titulo: 'Análise de Crédito Corporativo',
    categoria: 'Avançado',
    duracao: '4h00',
    descricao: 'Metodologia de análise de crédito para empresas de médio e grande porte.',
    video_url: null,
    ordem: 2,
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'curso-003',
    titulo: 'Originação de Operações',
    categoria: 'Prático',
    duracao: '3h00',
    descricao: 'Como prospectar e originar operações financeiras no mercado de capitais.',
    video_url: null,
    ordem: 3,
    created_at: '2024-03-01T10:00:00Z',
  },
];

export const mockProgressoCursos = [
  {
    id: 'prog-001',
    usuario_id: MOCK_USER_ID,
    curso_id: 'curso-001',
    progresso: 100,
    status: 'concluído',
    concluido_em: '2024-02-15T10:00:00Z',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-02-15T10:00:00Z',
  },
  {
    id: 'prog-002',
    usuario_id: MOCK_USER_ID,
    curso_id: 'curso-002',
    progresso: 60,
    status: 'em andamento',
    concluido_em: null,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-05-01T10:00:00Z',
  },
];

// ===================== MATERIAIS =====================
export const mockMateriais = [
  {
    id: 'mat-001',
    nome: 'Guia do Parceiro MAX CAPITAL',
    categoria: 'Guias',
    formato: 'PDF',
    tamanho: '2.5 MB',
    downloads: 150,
    arquivo_url: null,
    atualizado_em: '2024-06-01T10:00:00Z',
    created_at: '2024-01-01T10:00:00Z',
  },
  {
    id: 'mat-002',
    nome: 'Modelo de Apresentação Comercial',
    categoria: 'Templates',
    formato: 'PPTX',
    tamanho: '5.1 MB',
    downloads: 89,
    arquivo_url: null,
    atualizado_em: '2024-05-15T10:00:00Z',
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'mat-003',
    nome: 'Planilha de Análise Financeira',
    categoria: 'Ferramentas',
    formato: 'XLSX',
    tamanho: '1.2 MB',
    downloads: 210,
    arquivo_url: null,
    atualizado_em: '2024-04-01T10:00:00Z',
    created_at: '2024-01-15T10:00:00Z',
  },
];

// ===================== NOTÍCIAS =====================
export const mockNoticias = [
  {
    id: 'noticia-001',
    titulo: 'MAX CAPITAL atinge R$ 100M em operações',
    conteudo: 'A MAX CAPITAL atingiu a marca de R$ 100 milhões em operações estruturadas no primeiro semestre de 2024.',
    resumo: 'Marco histórico para a empresa.',
    imagem_url: null,
    categoria: 'Institucional',
    fonte: 'interno',
    publicado: true,
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'noticia-002',
    titulo: 'Novo programa de parceiros lançado',
    conteudo: 'Lançamos o novo programa de parceiros com benefícios exclusivos e comissões aumentadas.',
    resumo: 'Novas oportunidades para parceiros.',
    imagem_url: null,
    categoria: 'Programa',
    fonte: 'interno',
    publicado: true,
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2024-05-15T10:00:00Z',
  },
  {
    id: 'noticia-m01',
    titulo: 'Ibovespa sobe 1,2% com alta de commodities e fluxo estrangeiro',
    conteudo: 'O Ibovespa fechou em alta impulsionado por papéis de mineração e petróleo.',
    resumo: 'Bolsa brasileira avança com cenário externo favorável.',
    imagem_url: null,
    categoria: 'Bolsa',
    fonte: 'infomoney',
    fonte_url: 'https://www.infomoney.com.br/',
    publicado: true,
    created_at: '2026-02-20T09:00:00Z',
    updated_at: '2026-02-20T09:00:00Z',
  },
  {
    id: 'noticia-m02',
    titulo: 'Selic pode cair para 12,25% na próxima reunião do Copom',
    conteudo: 'Analistas projetam corte de 0,5 ponto percentual na taxa básica de juros.',
    resumo: 'Expectativa de queda nos juros anima mercado de renda fixa.',
    imagem_url: null,
    categoria: 'Economia',
    fonte: 'suno',
    fonte_url: 'https://suno.com.br/',
    publicado: true,
    created_at: '2026-02-20T08:30:00Z',
    updated_at: '2026-02-20T08:30:00Z',
  },
  {
    id: 'noticia-m03',
    titulo: 'Dólar recua para R$ 5,85 com entrada de capital externo',
    conteudo: 'A moeda americana registrou queda pelo terceiro dia consecutivo.',
    resumo: 'Fluxo de investidores estrangeiros pressiona câmbio para baixo.',
    imagem_url: null,
    categoria: 'Câmbio',
    fonte: 'valor',
    fonte_url: 'https://valor.globo.com/',
    publicado: true,
    created_at: '2026-02-20T10:15:00Z',
    updated_at: '2026-02-20T10:15:00Z',
  },
  {
    id: 'noticia-m04',
    titulo: 'FIIs de logística apresentam melhor rendimento do trimestre',
    conteudo: 'Fundos imobiliários de galpões logísticos superam CDI no acumulado do ano.',
    resumo: 'Setor logístico se destaca entre os fundos imobiliários.',
    imagem_url: null,
    categoria: 'FIIs',
    fonte: 'investidor10',
    fonte_url: 'https://investidor10.com.br/',
    publicado: true,
    created_at: '2026-02-19T14:00:00Z',
    updated_at: '2026-02-19T14:00:00Z',
  },
  {
    id: 'noticia-m05',
    titulo: 'B3 registra volume recorde de negociações em fevereiro',
    conteudo: 'A bolsa brasileira bateu recorde de volume financeiro diário.',
    resumo: 'Volume de negociações na B3 atinge R$ 42 bilhões em um único dia.',
    imagem_url: null,
    categoria: 'B3',
    fonte: 'b3',
    fonte_url: 'https://www.b3.com.br/',
    publicado: true,
    created_at: '2026-02-19T16:30:00Z',
    updated_at: '2026-02-19T16:30:00Z',
  },
  {
    id: 'noticia-m06',
    titulo: 'CRIs e CRAs ganham destaque com queda da Selic',
    conteudo: 'Certificados de recebíveis atraem investidores buscando retornos acima do CDI.',
    resumo: 'Mercado de crédito estruturado cresce com cenário de juros menores.',
    imagem_url: null,
    categoria: 'Renda Fixa',
    fonte: 'suno',
    fonte_url: 'https://suno.com.br/',
    publicado: true,
    created_at: '2026-02-18T11:00:00Z',
    updated_at: '2026-02-18T11:00:00Z',
  },
  {
    id: 'noticia-m07',
    titulo: 'Petrobras anuncia dividendos extraordinários de R$ 15 bi',
    conteudo: 'A estatal vai distribuir dividendos acima do esperado pelo mercado.',
    resumo: 'Ações da Petrobras sobem 3% após anúncio.',
    imagem_url: null,
    categoria: 'Ações',
    fonte: 'infomoney',
    fonte_url: 'https://www.infomoney.com.br/',
    publicado: true,
    created_at: '2026-02-18T09:45:00Z',
    updated_at: '2026-02-18T09:45:00Z',
  },
];

// ===================== NOTIFICAÇÕES =====================
export const mockNotificacoes = [
  {
    id: 'notif-001',
    destinatario_id: MOCK_USER_ID,
    tipo: 'sistema',
    titulo: 'Nova operação disponível',
    mensagem: 'Uma nova oportunidade de investimento está disponível para análise.',
    operacao_id: MOCK_OP_1_ID,
    status: 'enviada',
    created_at: '2024-06-01T10:00:00Z',
    lida_em: null,
  },
  {
    id: 'notif-002',
    destinatario_id: MOCK_USER_ID,
    tipo: 'sistema',
    titulo: 'Operação concluída',
    mensagem: 'A operação OP-2024-004 foi concluída com sucesso.',
    operacao_id: MOCK_OP_4_ID,
    status: 'lida',
    created_at: '2024-04-01T10:00:00Z',
    lida_em: '2024-04-01T12:00:00Z',
  },
];

// ===================== ROLES & ADMIN =====================
export const mockUserRoles = [
  { id: 'role-001', user_id: MOCK_USER_ID, role: 'admin' },
  { id: 'role-002', user_id: MOCK_USER_7_ID, role: 'admin' },
];

export const mockAdminEquipe = [
  {
    id: 'admin-001',
    user_id: MOCK_USER_ID,
    role: 'master',
    departamento: 'Diretoria',
    cargo: 'Diretor Geral',
    ativo: true,
    created_at: '2024-01-01T10:00:00Z',
  },
  {
    id: 'admin-002',
    user_id: MOCK_USER_7_ID,
    role: 'admin',
    departamento: 'Operações',
    cargo: 'Gerente de Operações',
    ativo: true,
    created_at: '2024-01-20T10:00:00Z',
  },
];

export const mockAdminPermissions = [
  { id: 'perm-001', role: 'master', resource: 'users', action: 'create', allowed: true },
  { id: 'perm-002', role: 'master', resource: 'users', action: 'read', allowed: true },
  { id: 'perm-003', role: 'master', resource: 'users', action: 'update', allowed: true },
  { id: 'perm-004', role: 'master', resource: 'users', action: 'delete', allowed: true },
  { id: 'perm-005', role: 'master', resource: 'empresas', action: 'create', allowed: true },
  { id: 'perm-006', role: 'master', resource: 'empresas', action: 'read', allowed: true },
  { id: 'perm-007', role: 'master', resource: 'empresas', action: 'update', allowed: true },
  { id: 'perm-008', role: 'master', resource: 'empresas', action: 'delete', allowed: true },
  { id: 'perm-009', role: 'master', resource: 'operacoes', action: 'create', allowed: true },
  { id: 'perm-010', role: 'master', resource: 'operacoes', action: 'read', allowed: true },
  { id: 'perm-011', role: 'master', resource: 'operacoes', action: 'update', allowed: true },
  { id: 'perm-012', role: 'master', resource: 'operacoes', action: 'delete', allowed: true },
  { id: 'perm-013', role: 'master', resource: 'teses', action: 'create', allowed: true },
  { id: 'perm-014', role: 'master', resource: 'teses', action: 'read', allowed: true },
  { id: 'perm-015', role: 'master', resource: 'teses', action: 'update', allowed: true },
  { id: 'perm-016', role: 'master', resource: 'teses', action: 'delete', allowed: true },
  { id: 'perm-017', role: 'master', resource: 'oportunidades', action: 'create', allowed: true },
  { id: 'perm-018', role: 'master', resource: 'oportunidades', action: 'read', allowed: true },
  { id: 'perm-019', role: 'master', resource: 'oportunidades', action: 'update', allowed: true },
  { id: 'perm-020', role: 'master', resource: 'oportunidades', action: 'delete', allowed: true },
  { id: 'perm-021', role: 'master', resource: 'cursos', action: 'create', allowed: true },
  { id: 'perm-022', role: 'master', resource: 'cursos', action: 'read', allowed: true },
  { id: 'perm-023', role: 'master', resource: 'cursos', action: 'update', allowed: true },
  { id: 'perm-024', role: 'master', resource: 'cursos', action: 'delete', allowed: true },
  { id: 'perm-025', role: 'master', resource: 'materiais', action: 'create', allowed: true },
  { id: 'perm-026', role: 'master', resource: 'materiais', action: 'read', allowed: true },
  { id: 'perm-027', role: 'master', resource: 'configuracoes', action: 'read', allowed: true },
  { id: 'perm-028', role: 'master', resource: 'configuracoes', action: 'update', allowed: true },
  { id: 'perm-029', role: 'master', resource: 'logs', action: 'read', allowed: true },
  { id: 'perm-030', role: 'master', resource: 'equipe', action: 'create', allowed: true },
  { id: 'perm-031', role: 'master', resource: 'equipe', action: 'read', allowed: true },
  { id: 'perm-032', role: 'master', resource: 'equipe', action: 'update', allowed: true },
  { id: 'perm-033', role: 'master', resource: 'equipe', action: 'delete', allowed: true },
  { id: 'perm-034', role: 'master', resource: 'chamados', action: 'read', allowed: true },
  { id: 'perm-035', role: 'master', resource: 'chamados', action: 'update', allowed: true },
  { id: 'perm-036', role: 'master', resource: 'comissoes', action: 'read', allowed: true },
  { id: 'perm-037', role: 'master', resource: 'comissoes', action: 'update', allowed: true },
  { id: 'perm-038', role: 'master', resource: 'profiles', action: 'read', allowed: true },
  { id: 'perm-039', role: 'master', resource: 'profiles', action: 'update', allowed: true },
  { id: 'perm-040', role: 'master', resource: 'noticias', action: 'create', allowed: true },
  { id: 'perm-041', role: 'master', resource: 'noticias', action: 'read', allowed: true },
  { id: 'perm-042', role: 'master', resource: 'noticias', action: 'update', allowed: true },
  { id: 'perm-043', role: 'master', resource: 'noticias', action: 'delete', allowed: true },
  { id: 'perm-044', role: 'master', resource: 'users', action: 'approve', allowed: true },
  { id: 'perm-045', role: 'master', resource: 'users', action: 'export', allowed: true },
  { id: 'perm-046', role: 'master', resource: 'operacoes', action: 'approve', allowed: true },
  { id: 'perm-047', role: 'master', resource: 'operacoes', action: 'export', allowed: true },
];

// ===================== CHAMADOS =====================
export const mockChamados = [
  {
    id: 'chamado-001',
    numero_chamado: 'CHM-001',
    usuario_id: MOCK_USER_ID,
    categoria: 'duvida_financeira',
    prioridade: 'media',
    status: 'aberto',
    assunto: 'Dúvida sobre comissões',
    descricao: 'Gostaria de entender melhor como funciona o cálculo de comissões sobre operações concluídas.',
    anexos: null,
    atribuido_a: null,
    resolvido_por: null,
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
    primeira_resposta_em: null,
    resolvido_em: null,
    fechado_em: null,
    avaliacao: null,
    feedback: null,
    usuario: { id: MOCK_USER_ID, nome: 'João Silva', email: 'joao@maxcapital.com.br', avatar_url: null },
  },
  {
    id: 'chamado-002',
    numero_chamado: 'CHM-002',
    usuario_id: MOCK_USER_4_ID,
    categoria: 'problema_tecnico',
    prioridade: 'alta',
    status: 'em_andamento',
    assunto: 'Erro ao cadastrar empresa',
    descricao: 'Ao tentar cadastrar a empresa Grãos do Cerrado, o sistema retorna erro de validação no campo CNPJ mesmo com formato correto.',
    anexos: null,
    atribuido_a: 'admin-002',
    resolvido_por: null,
    created_at: '2024-09-15T14:30:00Z',
    updated_at: '2024-09-16T09:00:00Z',
    primeira_resposta_em: '2024-09-16T09:00:00Z',
    resolvido_em: null,
    fechado_em: null,
    avaliacao: null,
    feedback: null,
    usuario: { id: MOCK_USER_4_ID, nome: 'Ana Beatriz Costa', email: 'ana.costa@parceiro.com', avatar_url: null },
  },
  {
    id: 'chamado-003',
    numero_chamado: 'CHM-003',
    usuario_id: MOCK_USER_2_ID,
    categoria: 'solicitacao_cadastro',
    prioridade: 'baixa',
    status: 'resolvido',
    assunto: 'Atualização de dados cadastrais',
    descricao: 'Preciso atualizar o endereço da empresa Energia Verde Ltda para o novo escritório.',
    anexos: null,
    atribuido_a: 'admin-001',
    resolvido_por: 'admin-001',
    created_at: '2024-08-10T11:00:00Z',
    updated_at: '2024-08-12T15:00:00Z',
    primeira_resposta_em: '2024-08-10T16:00:00Z',
    resolvido_em: '2024-08-12T15:00:00Z',
    fechado_em: null,
    avaliacao: 5,
    feedback: 'Resolvido rapidamente, obrigada!',
    usuario: { id: MOCK_USER_2_ID, nome: 'Maria Santos', email: 'maria@empresa.com', avatar_url: null },
  },
  {
    id: 'chamado-004',
    numero_chamado: 'CHM-004',
    usuario_id: MOCK_USER_5_ID,
    categoria: 'duvida',
    prioridade: 'media',
    status: 'aguardando_usuario',
    assunto: 'Como manifestar interesse em oportunidade',
    descricao: 'Gostaria de saber o processo para manifestar interesse na oportunidade Debênture Solar Norte.',
    anexos: null,
    atribuido_a: 'admin-002',
    resolvido_por: null,
    created_at: '2024-10-01T08:30:00Z',
    updated_at: '2024-10-02T10:00:00Z',
    primeira_resposta_em: '2024-10-01T14:00:00Z',
    resolvido_em: null,
    fechado_em: null,
    avaliacao: null,
    feedback: null,
    usuario: { id: MOCK_USER_5_ID, nome: 'Ricardo Mendes', email: 'ricardo@investimentos.com', avatar_url: null },
  },
  {
    id: 'chamado-005',
    numero_chamado: 'CHM-005',
    usuario_id: MOCK_USER_6_ID,
    categoria: 'erro_sistema',
    prioridade: 'urgente',
    status: 'em_andamento',
    assunto: 'Dashboard não carrega dados da operação',
    descricao: 'Desde ontem o dashboard não exibe os dados da operação OP-2024-008 da Solar Norte. Fica carregando infinitamente.',
    anexos: null,
    atribuido_a: 'admin-001',
    resolvido_por: null,
    created_at: '2024-10-10T07:00:00Z',
    updated_at: '2024-10-10T09:30:00Z',
    primeira_resposta_em: '2024-10-10T09:30:00Z',
    resolvido_em: null,
    fechado_em: null,
    avaliacao: null,
    feedback: null,
    usuario: { id: MOCK_USER_6_ID, nome: 'Fernanda Lima', email: 'fernanda@agro.com.br', avatar_url: null },
  },
  {
    id: 'chamado-006',
    numero_chamado: 'CHM-006',
    usuario_id: MOCK_USER_10_ID,
    categoria: 'sugestao',
    prioridade: 'baixa',
    status: 'fechado',
    assunto: 'Sugestão de melhoria no filtro de oportunidades',
    descricao: 'Seria interessante poder filtrar oportunidades por faixa de rentabilidade e prazo de investimento.',
    anexos: null,
    atribuido_a: 'admin-002',
    resolvido_por: 'admin-002',
    created_at: '2024-07-20T16:00:00Z',
    updated_at: '2024-07-25T10:00:00Z',
    primeira_resposta_em: '2024-07-21T09:00:00Z',
    resolvido_em: '2024-07-24T14:00:00Z',
    fechado_em: '2024-07-25T10:00:00Z',
    avaliacao: 4,
    feedback: 'Boa sugestão, espero que implementem!',
    usuario: { id: MOCK_USER_10_ID, nome: 'Camila Ferreira', email: 'camila@investidor.com.br', avatar_url: null },
  },
];

// ===================== CHAMADOS RESPOSTAS =====================
export const mockChamadosRespostas = [
  {
    id: 'resp-001',
    chamado_id: 'chamado-002',
    autor_id: MOCK_USER_7_ID,
    is_admin: true,
    mensagem: 'Olá Ana, identificamos o problema de validação do CNPJ. Estamos corrigindo e retornaremos em breve.',
    anexos: null,
    interno: false,
    created_at: '2024-09-16T09:00:00Z',
    autor: { id: MOCK_USER_7_ID, nome: 'Pedro Almeida', avatar_url: null },
  },
  {
    id: 'resp-002',
    chamado_id: 'chamado-003',
    autor_id: MOCK_USER_ID,
    is_admin: true,
    mensagem: 'Endereço atualizado conforme solicitado. Por favor, verifique se está correto.',
    anexos: null,
    interno: false,
    created_at: '2024-08-10T16:00:00Z',
    autor: { id: MOCK_USER_ID, nome: 'João Silva', avatar_url: null },
  },
  {
    id: 'resp-003',
    chamado_id: 'chamado-003',
    autor_id: MOCK_USER_2_ID,
    is_admin: false,
    mensagem: 'Confirmado, endereço correto. Obrigada!',
    anexos: null,
    interno: false,
    created_at: '2024-08-11T10:00:00Z',
    autor: { id: MOCK_USER_2_ID, nome: 'Maria Santos', avatar_url: null },
  },
  {
    id: 'resp-004',
    chamado_id: 'chamado-004',
    autor_id: MOCK_USER_7_ID,
    is_admin: true,
    mensagem: 'Ricardo, para manifestar interesse basta acessar a seção "Oportunidades", clicar na oportunidade desejada e clicar em "Manifestar Interesse". Você precisará aceitar os termos. Ficou alguma dúvida?',
    anexos: null,
    interno: false,
    created_at: '2024-10-01T14:00:00Z',
    autor: { id: MOCK_USER_7_ID, nome: 'Pedro Almeida', avatar_url: null },
  },
  {
    id: 'resp-005',
    chamado_id: 'chamado-005',
    autor_id: MOCK_USER_ID,
    is_admin: true,
    mensagem: 'Fernanda, estamos investigando o problema. Parece ser um cache desatualizado. Pode tentar limpar o cache do navegador?',
    anexos: null,
    interno: false,
    created_at: '2024-10-10T09:30:00Z',
    autor: { id: MOCK_USER_ID, nome: 'João Silva', avatar_url: null },
  },
];

// ===================== ADMIN LOGS =====================
export const mockAdminLogs = [
  {
    id: 'log-001',
    admin_id: 'admin-001',
    acao: 'criar',
    recurso: 'empresas',
    recurso_id: MOCK_EMPRESA_1_ID,
    descricao: 'Empresa Tech Solutions Ltda criada',
    dados_anteriores: null,
    dados_novos: { nome: 'Tech Solutions Ltda', cnpj: '12.345.678/0001-90' },
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-01-20T10:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-002',
    admin_id: 'admin-001',
    acao: 'criar',
    recurso: 'operacoes',
    recurso_id: MOCK_OP_1_ID,
    descricao: 'Operação OP-2024-001 criada para Tech Solutions Ltda',
    dados_anteriores: null,
    dados_novos: { numero_funil: 'OP-2024-001', valor_investimento: 2500000 },
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-05-01T10:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-003',
    admin_id: 'admin-001',
    acao: 'editar',
    recurso: 'operacoes',
    recurso_id: MOCK_OP_4_ID,
    descricao: 'Operação OP-2024-004 movida para Concluído',
    dados_anteriores: { etapa_atual: 'Negociação' },
    dados_novos: { etapa_atual: 'Concluído' },
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-04-01T10:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-004',
    admin_id: 'admin-002',
    acao: 'aprovar',
    recurso: 'usuarios',
    recurso_id: MOCK_USER_4_ID,
    descricao: 'Usuário Ana Beatriz Costa aprovado como parceiro',
    dados_anteriores: { status: 'pendente_aprovacao' },
    dados_novos: { status: 'ativo' },
    ip_address: '10.0.0.50',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-03-16T11:00:00Z',
    admin: { id: 'admin-002', cargo: 'Gerente de Operações', profile: { nome: 'Pedro Almeida', avatar_url: null } },
  },
  {
    id: 'log-005',
    admin_id: 'admin-001',
    acao: 'editar',
    recurso: 'empresas',
    recurso_id: MOCK_EMPRESA_3_ID,
    descricao: 'Empresa Energia Verde Ltda — endereço atualizado',
    dados_anteriores: { endereco_numero: '100' },
    dados_novos: { endereco_numero: '200' },
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-08-12T15:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-006',
    admin_id: 'admin-001',
    acao: 'criar',
    recurso: 'operacoes',
    recurso_id: MOCK_OP_7_ID,
    descricao: 'Operação OP-2024-007 criada para FinBank Digital S.A.',
    dados_anteriores: null,
    dados_novos: { numero_funil: 'OP-2024-007', valor_investimento: 12000000 },
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-06-15T10:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-007',
    admin_id: 'admin-002',
    acao: 'editar',
    recurso: 'chamados',
    recurso_id: 'chamado-002',
    descricao: 'Chamado CHM-002 atribuído e status alterado para em_andamento',
    dados_anteriores: { status: 'aberto', atribuido_a: null },
    dados_novos: { status: 'em_andamento', atribuido_a: 'admin-002' },
    ip_address: '10.0.0.50',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-09-16T08:45:00Z',
    admin: { id: 'admin-002', cargo: 'Gerente de Operações', profile: { nome: 'Pedro Almeida', avatar_url: null } },
  },
  {
    id: 'log-008',
    admin_id: 'admin-001',
    acao: 'desativar',
    recurso: 'usuarios',
    recurso_id: MOCK_USER_9_ID,
    descricao: 'Usuário Marcos Vinícius Souza desativado por inatividade',
    dados_anteriores: { status: 'ativo' },
    dados_novos: { status: 'inativo' },
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-10-01T14:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-009',
    admin_id: 'admin-001',
    acao: 'criar',
    recurso: 'teses',
    recurso_id: 'tese-007',
    descricao: 'Tese Infraestrutura & Saneamento criada',
    dados_anteriores: null,
    dados_novos: { titulo: 'Infraestrutura & Saneamento', valor_min: 50000000 },
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-07-01T10:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-010',
    admin_id: 'admin-002',
    acao: 'export',
    recurso: 'operacoes',
    recurso_id: null,
    descricao: 'Exportação de relatório de operações — período jan-set/2024',
    dados_anteriores: null,
    dados_novos: null,
    ip_address: '10.0.0.50',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-10-05T16:30:00Z',
    admin: { id: 'admin-002', cargo: 'Gerente de Operações', profile: { nome: 'Pedro Almeida', avatar_url: null } },
  },
  {
    id: 'log-011',
    admin_id: 'admin-001',
    acao: 'login',
    recurso: 'sistema',
    recurso_id: null,
    descricao: 'Login administrativo realizado',
    dados_anteriores: null,
    dados_novos: null,
    ip_address: '192.168.1.100',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-10-12T08:00:00Z',
    admin: { id: 'admin-001', cargo: 'Diretor Geral', profile: { nome: 'João Silva', avatar_url: null } },
  },
  {
    id: 'log-012',
    admin_id: 'admin-002',
    acao: 'login',
    recurso: 'sistema',
    recurso_id: null,
    descricao: 'Login administrativo realizado',
    dados_anteriores: null,
    dados_novos: null,
    ip_address: '10.0.0.50',
    user_agent: 'Mozilla/5.0',
    created_at: '2024-10-12T08:15:00Z',
    admin: { id: 'admin-002', cargo: 'Gerente de Operações', profile: { nome: 'Pedro Almeida', avatar_url: null } },
  },
];

// ===================== MANIFESTAÇÕES DE INTERESSE =====================
export const mockManifestacoes = [
  {
    id: 'manif-001',
    oportunidade_id: 'oport-001',
    investidor_id: MOCK_USER_3_ID,
    valor: 500000,
    status: 'pendente',
    created_at: '2024-05-15T10:00:00Z',
  },
  {
    id: 'manif-002',
    oportunidade_id: 'oport-003',
    investidor_id: MOCK_USER_5_ID,
    valor: 1000000,
    status: 'aprovada',
    created_at: '2024-07-01T10:00:00Z',
  },
  {
    id: 'manif-003',
    oportunidade_id: 'oport-005',
    investidor_id: MOCK_USER_10_ID,
    valor: 200000,
    status: 'pendente',
    created_at: '2024-09-15T10:00:00Z',
  },
];

// ===================== COMISSÕES =====================
export const mockComissoes = [
  {
    id: 'comissao-001',
    usuario_id: MOCK_USER_ID,
    operacao_id: MOCK_OP_4_ID,
    valor: 15000,
    percentual: 1.0,
    status: 'paga',
    tipo: 'originacao',
    data_pagamento: '2024-04-15T10:00:00Z',
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'comissao-002',
    usuario_id: MOCK_USER_4_ID,
    operacao_id: MOCK_OP_6_ID,
    valor: 75000,
    percentual: 0.5,
    status: 'pendente',
    tipo: 'originacao',
    data_pagamento: null,
    created_at: '2024-10-10T10:00:00Z',
  },
  {
    id: 'comissao-003',
    usuario_id: MOCK_USER_ID,
    operacao_id: MOCK_OP_7_ID,
    valor: 60000,
    percentual: 0.5,
    status: 'aprovada',
    tipo: 'indicacao',
    data_pagamento: null,
    created_at: '2024-10-05T10:00:00Z',
  },
];

// ===================== DATA MAP =====================
export const mockDataMap: Record<string, any[]> = {
  profiles: mockProfiles,
  profile_details: mockProfileDetails,
  empresas: mockEmpresas,
  operacoes: mockOperacoes,
  movimentacoes_historico: mockMovimentacoesHistorico,
  membros_rede: mockMembrosRede,
  indicacoes: mockIndicacoes,
  teses_investimento: mockTesesInvestimento,
  oportunidades_investimento: mockOportunidadesInvestimento,
  cursos: mockCursos,
  progresso_cursos: mockProgressoCursos,
  materiais: mockMateriais,
  noticias: mockNoticias,
  notificacoes: mockNotificacoes,
  user_roles: mockUserRoles,
  admin_equipe: mockAdminEquipe,
  admin_permissions: mockAdminPermissions,
  chamados: mockChamados,
  chamados_respostas: mockChamadosRespostas,
  admin_logs: mockAdminLogs,
  manifestacoes_interesse: mockManifestacoes,
  comissoes: mockComissoes,
  scheduled_reports: [],
  integrity_checks: [],
  configuracoes: [],
  formularios: [],
  audit_logs: [],
  configuracoes_sistema: [],
  operacoes_historico: [],
};

export const MOCK_USER_ID_EXPORT = MOCK_USER_ID;
